pipeline {
    agent { 
        node {
            label 'docker-agent-python'
            }
      }
    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10')
    }
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo "Start Building..."
                sh '''
                '''
                echo "Finish Building..."
            }
        }
        stage('Test') {
            steps {
                echo "Start Testing..."
                sh '''
                '''
                echo "Finish Testing..."
            }
        }
        stage('Deliver') {
            steps {
                echo "Start Deliver..."
                sh '''
                '''
                echo "Finish Deliver..."
            }
        }
    }
}