pipeline {
    agent {
        docker { image 'jenkins/agent:latest-alpine-jdk11' }
    }
    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10')
    }
    stages {
        stage('Checkout') {
            steps {
                echo "Start Checkout..."
                echo 'Make the output directory'
                sh 'mkdir -p build'
                echo 'Cloning files from "main"'
                dir('build') {
                    checkout scmGit(
                        branches: [[name: '*/main']], 
                        extensions: [cloneOption(depth: 1, noTags: true, reference: '', shallow: true, timeout: 200)], 
                        userRemoteConfigs: [[credentialsId: 'jenkins-roguelike-source', url: 'https://github.com/TreemanUA/NerdLike.git']])
                }   
                echo "Finish Checkout..."
            }  
        }       
        stage('Test') {
            steps {
                echo "Start Testing..."
                sh '''
                echo "doing testing stuff.."
                '''
                echo "Finish Testing..."
            }
        }
        stage('Deliver') {
            steps {
                echo "Start Deliver..."
                sh '''
                echo "doing delivery stuff.."
                '''
                echo "Finish Deliver..."
            }
        }
    }
}