pipeline {
    agent {
        docker { image 'jenkins/agent:latest-alpine-jdk11' }
    }
    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10')
    }
    stages {
        stage('Checkout') {
            steps {
                echo "Start Checkout..."
                echo 'Make the output directory'
                sh 'mkdir -p build'
                echo 'Cloning files from "main"'
                dir('build') {
                    checkout scmGit(
                        branches: [[name: '*/main']], 
                        extensions: [cloneOption(depth: 1, noTags: true, reference: '', shallow: true, timeout: 200)], 
                        userRemoteConfigs: [[credentialsId: 'jenkins-roguelike-source', url: 'https://github.com/TreemanUA/NerdLike.git']])
                }   
                echo "Finish Checkout..."
            }  
        }       
        agent {
            docker {
                image 'maven:3.9.1-eclipse-temurin-11-alpine'
                args '-v $HOME/.m2:/root/.m2'
            }
        }
        stages {
            stage('Build') {
                steps {
                    sh 'mvn -B'
                }
            }
        }
    }
}